name: Publish Docker Image
on:
  workflow_run:
    workflows: ['Build and Test .NET']                     # runs after CI workflow
    types:
      - completed
jobs:
  build_image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ${{ github.workspace }}/Source/SteveLabs.DockerBuildTest/Dockerfile
          push: false
          tags: test
          labels: test
