name: Publish Docker Image
on:
  workflow_run:
    workflows: ['Build and Test .NET']                     # runs after CI workflow
    types:
      - completed
jobs:
  build_image:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Çheckout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Echo Workspace
        run: ls -ah ${{ github.workspace }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: sdryan85/docker-build-test
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/Source/SteveLabs.DockerBuildTest
          file: ${{ github.workspace }}/Source/SteveLabs.DockerBuildTest/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
