name: 'Unit Test Report'
on:
  workflow_run:
    workflows: ['Build and Test .NET']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    name: Generate Unit Test Report
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: Unit Test Results       # Artifact name
        name: Unit Test Results           # Name of the check run which will be created
        path: 'test-results.trx'          # Path to test results (inside artifact .zip)
        reporter: dotnet-trx              # Format of test results
